import { expect, test } from "bun:test"
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"

import { canonicalJsonDigest } from "../src/catalog/canonicalJsonDigest.js"
import { canonicalJsonStringify } from "../src/catalog/canonicalJsonStringify.js"
import { catalogEntryPropertyCreate } from "../src/catalog/catalogEntryPropertyCreate.js"
import { catalogListsCheck } from "../src/catalog/catalogListsCheck.js"
import { catalogListsRender } from "../src/catalog/catalogListsRender.js"
import { catalogListsWrite } from "../src/catalog/catalogListsWrite.js"

const imageEntry = {
  class: "image" as const,
  folders: ["home"],
  basename: "hero",
  key: "1920x1080-webp",
  path: "images/home/hero_1920x1080-webp_v1.webp",
  mediaType: "image/webp",
  metadata: {
    kind: "image" as const,
    width: 1920,
    height: 1080,
    format: "webp" as const,
    colorSpace: "srgb",
    alpha: false,
    orientationApplied: true,
    frameCount: 1,
    animated: false,
    alt: "Hero",
    aiProvenance: null,
  },
}

test("canonical JSON sorts object keys without changing array order", () => {
  expect(canonicalJsonStringify({ z: 1, a: { y: true, b: 2 }, list: ["b", "a"] })).toBe(
    '{"a":{"b":2,"y":true},"list":["b","a"],"z":1}',
  )
  expect(canonicalJsonDigest({ a: 1, b: 2 })).toBe(canonicalJsonDigest({ b: 2, a: 1 }))
})

test("catalog properties use folders, basename, and output key", () => {
  expect(catalogEntryPropertyCreate(imageEntry)).toBe("home_hero_1920x1080_webp")
  expect(catalogEntryPropertyCreate({ ...imageEntry, folders: [], basename: "9-lives", key: "small-large" })).toBe(
    "i9_lives_small_large",
  )
})

test("catalog renderer emits sorted flat lists and empty lists", () => {
  const rendered = catalogListsRender(
    [imageEntry, { ...imageEntry, key: "662x372-webp", path: "images/home/hero_662x372-webp_v1.webp" }],
    { importPath: "@example/assets", rendererVersion: "7" },
  )

  expect(rendered.success).toBe(true)
  if (!rendered.success) return

  expect(rendered.data.digest).toBe("74deae9f6aed26f1f02696331dfaa87089b6f00f20dfd472a18c21089e22ab8c")
  expect(rendered.data.imageList).toContain('export const imageList = {\n  "home_hero_1920x1080_webp":')
  expect(rendered.data.imageList.indexOf("home_hero_1920x1080_webp")).toBeLessThan(
    rendered.data.imageList.indexOf("home_hero_662x372_webp"),
  )
  expect(rendered.data.videoList).toBe(
    [
      'import type { CatalogVideo } from "@example/assets"',
      "",
      "// Auto-generated by @adaptive-ds/assets-service. Do not edit.",
      "// schema: assets.catalog.v1",
      `// catalog-digest: ${rendered.data.digest}`,
      "// renderer-version: 7",
      "export const videoList = {} as const satisfies Record<string, CatalogVideo>",
      "",
    ].join("\n"),
  )
})

test("catalog renderer rejects generated property collisions", () => {
  const result = catalogListsRender([
    imageEntry,
    { ...imageEntry, key: "1920x1080_webp", path: "images/home/other.webp" },
  ])

  expect(result.success).toBe(false)
  if (!result.success) expect(result.errorMessage).toContain("generated property collision")
})

test("catalog renderer escapes TypeScript string values", () => {
  const result = catalogListsRender([
    {
      ...imageEntry,
      basename: 'hero"quote',
      path: "images/home/hero\u2028quote.webp",
    },
  ])

  expect(result.success).toBe(true)
  if (result.success) {
    expect(result.data.imageList).toContain('hero\\"quote')
    expect(result.data.imageList).toContain("\\u2028")
  }
})

test("catalog list writes are atomic and check exact bytes", async () => {
  const rendered = catalogListsRender([imageEntry])
  expect(rendered.success).toBe(true)
  if (!rendered.success) return

  const directory = await mkdtemp(join(tmpdir(), "assets-service-catalog-"))
  const files = {
    imageListPath: join(directory, "imageList.ts"),
    videoListPath: join(directory, "videoList.ts"),
    fontListPath: join(directory, "fontList.ts"),
  }

  try {
    const written = await catalogListsWrite(files, rendered.data)
    expect(written.success).toBe(true)
    expect(await catalogListsCheck(files, rendered.data)).toEqual({ success: true, data: true })

    await writeFile(files.imageListPath, `${await readFile(files.imageListPath, "utf8")}\n`)
    expect(await catalogListsCheck(files, rendered.data)).toEqual({ success: true, data: false })
  } finally {
    await rm(directory, { recursive: true, force: true })
  }
})
