import { resultErrorCreate } from "../schemas/resultErrorCreate.js"
import type { Result } from "../schemas/resultSchema.js"
import { canonicalJsonDigest } from "./canonicalJsonDigest.js"
import { canonicalJsonStringify } from "./canonicalJsonStringify.js"
import { catalogEntriesCanonicalize } from "./catalogEntriesCanonicalize.js"
import { catalogEntryPropertyCreate } from "./catalogEntryPropertyCreate.js"
import type { CatalogEntry } from "./catalogEntrySchema.js"

const defaultImportPath = "@adaptive-ds/assets-service"
const defaultSchema = "assets.catalog.v1"
const defaultRendererVersion = "1"

const typesByClass = {
  image: "CatalogImage",
  video: "CatalogVideo",
  font: "CatalogFont",
  document: "CatalogDocument",
} as const

const stringLiteralCreate = (value: string): string =>
  JSON.stringify(value)
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029")

const listContentCreate = (
  className: CatalogEntry["class"],
  entries: readonly CatalogEntry[],
  digest: string,
  importPath: string,
  schema: string,
  rendererVersion: string,
): string => {
  const map = Object.fromEntries(
    entries.filter((entry) => entry.class === className).map((entry) => [catalogEntryPropertyCreate(entry), entry]),
  )
  const body = JSON.stringify(JSON.parse(canonicalJsonStringify(map)), null, 2)
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029")

  return [
    `import type { ${typesByClass[className]} } from ${stringLiteralCreate(importPath)}`,
    "",
    "// Auto-generated by @adaptive-ds/assets-service. Do not edit.",
    `// schema: ${schema}`,
    `// catalog-digest: ${digest}`,
    `// renderer-version: ${rendererVersion}`,
    `export const ${className}List = ${body} as const satisfies Record<string, ${typesByClass[className]}>`,
    "",
  ].join("\n")
}

export const catalogListsRender = (
  entries: readonly unknown[],
  options: { importPath?: string; schema?: string; rendererVersion?: string } = {},
): Result<{ imageList: string; videoList: string; fontList: string; documentList: string; digest: string }> => {
  const op = "catalogListsRender"
  const canonical = catalogEntriesCanonicalize(entries)
  if (!canonical.success) return resultErrorCreate(op, canonical.errorMessage, canonical.rawData)

  const digest = canonicalJsonDigest(canonical.data)
  const importPath = options.importPath ?? defaultImportPath
  const schema = options.schema ?? defaultSchema
  const rendererVersion = options.rendererVersion ?? defaultRendererVersion

  return {
    success: true,
    data: {
      imageList: listContentCreate("image", canonical.data, digest, importPath, schema, rendererVersion),
      videoList: listContentCreate("video", canonical.data, digest, importPath, schema, rendererVersion),
      fontList: listContentCreate("font", canonical.data, digest, importPath, schema, rendererVersion),
      documentList: listContentCreate("document", canonical.data, digest, importPath, schema, rendererVersion),
      digest,
    },
  }
}
